{{- if and .Values.backend.enabled .Values.global.features.opaqueIds.autoGenerateKey }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "mongodhara.backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Release.Name }}-creds"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "mongodhara.backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-api
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodhara.backend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
